apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "a2ml.fullname" . }}
  labels:
    {{- include "a2ml.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "a2ml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "a2ml.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "a2ml.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "a2ml.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/bash", "-c"]
          args: ["a2ml worker --concurrency={{ .Values.workerConcurrency }}"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.vault.enabled }}
          - name: AZURE_CREDENTIALS_PATH
            value: /vault/secrets/azure-creds
          {{- end }}
          - name: BROKER_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "a2ml.fullname" . }}
                key: brokerUrl
          {{- if .Values.minio.enabled }}
          - name: S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "a2ml.fullname" . }}
                key: s3EndpointUrl
          {{- end }}
          {{- include "a2ml.extraEnvironmentVars" . | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
