{{- if .Values.kedaAutoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "a2ml.fullname" . }}
spec:
  scaleTargetRef:
    name: {{ include "a2ml.fullname" . }}
  pollingInterval: {{ .Values.kedaAutoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.kedaAutoscaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.kedaAutoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.kedaAutoscaling.maxReplicaCount }}
  triggers:
  - type: rabbitmq
    metadata:
      includeUnacked: {{ .Values.kedaAutoscaling.includeUnacked | quote }}
      queueName: "{{ .Values.kedaAutoscaling.queueName }}"
      hostFromEnv: BROKER_HTTP_URL
      queueLength: {{ .Values.kedaAutoscaling.queueLength | quote }}
{{- end }}
