apiVersion: v1
kind: Secret
metadata:
  name: {{ template "a2ml.fullname" . }}
  labels:
    app: {{ template "a2ml.name" . }}
    chart: {{ template "a2ml.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  brokerUrl: {{ .Values.brokerUrl | b64enc }}
  {{- if .Values.minio.enabled }}
  s3EndpointUrl: {{ include "a2ml.s3EndpointUrl" . | b64enc }}
  {{- end }}
