---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: auger-creds
  labels:
    auger.ai/component-name: credentials
data:
  brokerHttpUrl: {{ .Values.brokerHttpUrl | b64enc }}
  brokerUrl: {{ .Values.brokerUrl | b64enc }}
